title:haojieli
name: haojieli
author: haojieli
baseurl: 
description: 李豪杰丨90后软件开发工程师
github: http://www.github.com/hjieli
email: 2252487366@qq.com
location: 42°2'16"N   70°12'47"W
disqus: diqus-username

##Make sure to edit the above fields, especially for disqus.


highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
